from django.urls import path
from .views import CandidateViewSet, CandidateSearchAPIView

# Define urlpatterns for both viewsets and search endpoint
urlpatterns = [
    # Include URLs generated by the router
    path('', CandidateViewSet.as_view({'get': 'list', 'post': 'create'}), name='candidate-list'),
    # Add a separate endpoint for search
    path('search/', CandidateSearchAPIView.as_view(), name='search'),
]
